debug: false

logging:
  level:
    com.example.extendablechattingbe: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chatdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: extendable-chatting-be-v1-2022-08-29.secret_key
  token-expired-time-ms: 864000000
